### PR TITLE
Support for 5s(N51AP)/9.0.2

### PR DESCRIPTION
**Pull request by goodbest**
Add support for iPhone6,1 / 9.0.2
See https://github.com/Siguza/cl0ver/issues/23

### CODE REVIEW

**Comment by Siguza** [comment]
Perfect, thanks! :D

**Comment by andreags4** [comment]
Does this offset work for the N53AP model too?
Because in the README i see "both models"

**Comment by Siguza** [comment]
Yes.

**Comment by andreags4** [comment]
Oh ok then you should add it in the notes, or change the name of the file because I got a bit confused and I don't want other people to get confused too..

Il giorno 11 feb 2017, alle ore 8:25 PM, Siguza <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Yes.

**Comment by Siguza** [comment]
3c84501cda7f6335f5c72cf670e8ff33e0927f57 Done.

**Pull request merged**
